#!/bin/zsh

ws="$(aerospace list-workspaces --focused)"
[ -z "$ws" ] && exit 0

aerospace list-windows --workspace "$ws" \
  --format '%{window-id}' \
| while IFS= read -r window_id; do
  [ -z "$window_id" ] && continue
  aerospace layout --window-id "$window_id" tiling
  aerospace layout --window-id "$window_id" tiles
done

aerospace flatten-workspace-tree
aerospace balance-sizes
