[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = "joshdick/onedark.vim"
hook_add = """
  colorscheme onedark
"""

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = "Shougo/ddc.vim"
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter', 'CursorHold', 'CmdlineEnter']
hook_source = """
  source $HOME/.config/nvim/plugins/ddc.rc.vim
"""

[[plugins]]
repo = "Shougo/pum.vim"

[[plugins]]
repo = "Shougo/ddc-around"

[[plugins]]
repo = "LumaKernel/ddc-file"

[[plugins]]
repo = "Shougo/ddc-matcher_head"

[[plugins]]
repo = "Shougo/ddc-sorter_rank"

[[plugins]]
repo = "Shougo/ddc-converter_remove_overlap"

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
  call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
hook_source= '''
  source $HOME/.config/nvim/plugins/nvim-lspconfig.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'ddc.vim'
depends = ['vim-vsnip-integ']
hook_add = '''
  source $HOME/.config/nvim/plugins/vim-vsnip.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = 'ddc.vim'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = "matsui54/denops-signature_help"

[[plugins]]
repo = "mattn/vim-sonictemplate"
hook_add = """
  let g:sonictemplate_vim_template_dir = [
    \ '$HOME/.vim/template',
  \]
"""

[[plugins]]
repo = "simeji/winresizer"


[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = "markonm/traces.vim"

[[plugins]]
repo = "kamykn/spelunker.vim"
hook_add = """
  let g:enable_spelunker_vim = 1
  let g:spelunker_check_type = 2
"""

[[plugins]]
repo = "ntpeters/vim-better-whitespace"
