[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = "joshdick/onedark.vim"
hook_add = """
  colorscheme onedark
"""

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source $HOME/.config/nvim/plugins/fzf.rc.vim
'''

[[plugins]]
repo = "Shougo/ddc.vim"
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter', 'CursorHold', 'CmdlineEnter']
hook_source = """
  source $HOME/.config/nvim/plugins/ddc.rc.vim
"""

[[plugins]]
repo = "Shougo/pum.vim"

[[plugins]]
repo = "Shougo/ddc-around"

[[plugins]]
repo = "LumaKernel/ddc-file"

[[plugins]]
repo = "Shougo/ddc-matcher_head"

[[plugins]]
repo = "Shougo/ddc-sorter_rank"

[[plugins]]
repo = "Shougo/ddc-converter_remove_overlap"

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'
hook_source = '''
  call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
hook_source= '''
  source $HOME/.config/nvim/plugins/nvim-lspconfig.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'ddc.vim'
depends = ['vim-vsnip-integ']
hook_add = '''
  source $HOME/.config/nvim/plugins/vim-vsnip.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = 'ddc.vim'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = "matsui54/denops-signature_help"

[[plugins]]
repo = "mattn/vim-goimports"
hook_add = """
  let g:goimports = 1
"""

[[plugins]]
repo = "kyoh86/vim-go-coverage"
on_ft = ["go"]

[[plugins]]
repo = "mattn/vim-goaddtags"
on_ft = ["go"]

[[plugins]]
repo = "mattn/vim-goimpl"
on_ft = ["go"]

[[plugins]]
repo = "mattn/vim-gomod"
on_ft = ["go"]

[[plugins]]
repo = "hashivim/vim-terraform"
on_ft = ["tf"]

[[plugins]]
repo = "mattn/vim-sonictemplate"
hook_add = """
  let g:sonictemplate_vim_template_dir = [
    \ '$HOME/.vim/template',
  \]
"""

[[plugins]]
repo = "ntpeters/vim-better-whitespace"
[[plugins]]
repo = "simeji/winresizer"
[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = """
  nmap s <Plug>(easymotion-overwin-f2)
"""

[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = "markonm/traces.vim"

[[plugins]]
repo = "kamykn/spelunker.vim"
hook_add = """
  let g:enable_spelunker_vim = 1
  let g:spelunlker_check_type = 2
"""

[[plugins]]
repo = "voldikss/vim-floaterm"
hook_add = """
  let g:floaterm_autoclose = 1
"""
hook_source = '''
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <M-t> <C-\><C-n>:FloatermToggle<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <C-t> <C-\><C-n>:FloatermNew<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <C-k> <C-\><C-n>:FloatermPrev<CR>
  autocmd vimrc User FloatermOpen tnoremap <buffer> <silent> <C-j> <C-\><C-n>:FloatermNext<CR>

  autocmd vimrc QuitPre * FloatermKill!
'''
