tap 'homebrew/cask'
tap 'homebrew/core'
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

brew "coreutils"
brew "vim"
brew "git"
brew "ghq"
brew "kubernetes-cli"
brew "kubectx"
brew "fzf"
brew "tfenv"
brew "bat"
brew "curl", link: true
brew "wget"
brew "jq"
brew "gawk"
brew "mas"
brew "ripgrep"
brew "git-delta"
brew "go"
brew "deno"

cask "google-cloud-sdk"
cask "1password"
cask "discord"
cask "slack"
cask "alfred"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "visual-studio-code"
cask "spotify"
cask "iterm2"
cask "clipy"

cask "font-hack-nerd-font"

mas "RunCat", id: 1429033973
