[[plugins]]
repo = 'simeji/winresizer'
on_event = 'BufEnter'

[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'BufEnter'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
on_cmd = 'Template'
lua_post_source = '''
  vim.g.sonictemplate_vim_template_dir = { "$HOME/.vim/template" }
'''

[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_event = 'BufEnter'

[[plugins]]
repo = 'lambdalisue/guise.vim'
on_event = 'BufEnter'

[[plugins]]
repo = 'unblevable/quick-scope'
on_event = 'BufEnter'
hook_add = '''
  augroup qs_colors
    autocmd!
    autocmd ColorScheme * highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
    autocmd ColorScheme * highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
  augroup END
'''
lua_post_source = '''
  vim.g.qs_hi_priority = 2
  vim.g.qs_max_chars = 80
  vim.g.qs_lazy_highlight = 0
  vim.g.qs_buftype_blacklist = { "terminal", "nofile" }
'''

[[plugins]]
repo = 'nvim-tree/nvim-tree.lua'
on_cmd = ["NvimTreeToggle"]
lua_post_source = '''
  vim.g.loaded_netrw = 1
  vim.g.loaded_netrwPlugin = 1

  require("nvim-tree").setup({
    sort_by = "case_sensitive",
    renderer = {
      group_empty = true,
    },
    filters = {
      dotfiles = true,
    },
  })
'''

[[plugins]]
repo = 'numToStr/FTerm.nvim'
on_event = 'BufEnter'
lua_add = '''
  vim.keymap.set("n", "T", '<C-\\><C-n><CMD>lua require("FTerm").toggle()<CR>')
'''
lua_post_source = '''
  require 'FTerm'.setup({
    border     = 'double',
    dimensions = {
      height = 0.9,
      width = 0.9,
    },
  })
'''

[[plugins]]
repo = 'kamykn/spelunker.vim'
on_event = 'BufEnter'
lua_add = '''
  vim.g.enable_spelunker_vim = 1
  vim.g.spelunker_check_type = 2
'''
