[[plugins]]
repo = 'kyoh86/vim-go-coverage'
on_ft = ['go']

[[plugins]]
repo = 'mattn/vim-goaddtags'
on_ft = ['go']

[[plugins]]
repo = 'mattn/vim-goimpl'
on_ft = ['go']

[[plugins]]
repo = 'mattn/vim-gomod'
on_ft = ['go']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
lua_add = '''
  vim.g.goimports = 1
'''
