name: Deno CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [vx.x.x]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4.2.2
     - name: Setup Deno
       uses: denoland/setup-deno@v2.0.1
       with:
         deno-version: ${{ matrix.version }}
     - name: Check format
       working-directory: ./cli
       run: deno fmt --check
     - name: Check lint
       working-directory: ./cli
       run: deno lint
     - name: Run
       run: make logo
