name: Lint
on:
  push:
  pull_request:

jobs:
  run-secretlint:
    name: "Secretlint only on changed files"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: setup get-diff-action
        uses: technote-space/get-diff-action@v6.1.2
      - name: setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: lint with Secretlint
        run: npx --no-install secretlint ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF && !env.MATCHED_FILES
