name: Lint
on:
  push:
  pull_request:

jobs:
  run-secretlint:
    name: "Secretlint only on changed files"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: setup get-diff-action
        uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # ratchet:technote-space/get-diff-action@v6.1.2
      - name: Run secretlint command on docker
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # ratchet:addnab/docker-run-action@v3
        with:
          image: secretlint/secretlint:v5.1.1
          options: >
            -v ${{ github.workspace }}:${{ github.workspace }}
            -w=${{ github.workspace }}
            --rm
          run: secretlint ${{ env.GIT_DIFF_FILTERED }} # run only on changed files
