[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
  source /Users/s11591/.vim/toml/plugins/lightline.rc.vim
"""

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
on_i = 1
#rev = 'release'
hook_add = '''
  source /Users/s11591/.vim/toml/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
